In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math 
import random

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn import model_selection
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from keras.regularizers import l2


In [ ]:
from sklearn.datasets import make_blobs
from keras.layers import LeakyReLU
from keras.layers import Dense
from keras.layers import BatchNormalization
from keras.models import Sequential
from keras.optimizers import Adam , SGD , Adagrad , Adadelta , Adamax
from keras.utils import to_categorical
from matplotlib import pyplot

In [ ]:
traindf = pd.read_csv('train_age_dataset.csv')
testdf = pd.read_csv('test_age_dataset.csv')

In [ ]:
acc = np.zeros((30,2))

n1 = 26


In [ ]:
from sklearn.utils import shuffle
from sklearn.preprocessing import StandardScaler
view_df = shuffle(traindf, random_state=2)



In [ ]:
view_df.value_counts('age_group')
an = random.randint(11,25)

In [ ]:
a = view_df[view_df['age_group']==4].head(1)
b=view_df.loc[view_df['age_group']!= 4]
c=view_df.loc[view_df['age_group']== 4]
view_df = pd.concat([a,b])
c = pd.concat([c,b])
print(c.shape)

(488877, 27)


In [ ]:
a = testdf.corr()
a.to_csv('correlation.csv')

In [ ]:
c4 = c.to_numpy()
X4 = c4[:,:n1]
Y4 = c4[:,n1:]
X4=np.asarray(X4)
scaler = StandardScaler()
X4 = scaler.fit_transform(X4)
print(X4,Y4)

[[-1.02985182 -2.2497022   0.0571564  ... -0.32899668 -0.30870976
   0.01631266]
 [ 1.57321727  0.29729231  0.0571564  ... -0.22304085  1.00141458
   0.01673566]
 [-1.5232706   0.10627878 -2.26460915 ... -0.3327465  -0.31546154
  -0.01741276]
 ...
 [-0.06974123  0.30258928  0.0571564  ... -0.3327465  -0.15085202
  -0.167788  ]
 [ 1.12722593 -2.3138851   0.0571564  ... -0.32812772 -0.30922425
   1.92766137]
 [-1.00189406 -0.02800575  0.0571564  ... -0.11690286  0.17033727
   0.00800338]] [[4.]
 [4.]
 [4.]
 ...
 [1.]
 [3.]
 [1.]]


In [ ]:

view_df=view_df.drop(view_df.columns[[]],axis=1)
view_df.head()

Unnamed: 0    userId  ...       avgt2  age_group
207569      110117   1378972  ...  180.784615          4
272831       60968  30229447  ...    0.000000          1
108175      265796  49113059  ...    0.000000          1
3201        528906  37399457  ...  196.500000          2
462335       14413  52648664  ...    0.000000          1

[5 rows x 27 columns]

In [ ]:
x_y = view_df.to_numpy()
X = x_y[:,:n1]
Y = x_y[:,n1:]
X=np.asarray(X)
scaler = StandardScaler()
X = scaler.fit_transform(X)
trainX, testX = X[:300000, :], X[300000:, :]
trainy, testy = Y[:300000], Y[300000:]
m = Y.shape[0]

In [ ]:
print(trainy)

[[4.]
 [1.]
 [1.]
 ...
 [2.]
 [1.]
 [3.]]


In [ ]:
print(Y)
print(trainX.shape)

[[4.]
 [1.]
 [1.]
 ...
 [1.]
 [3.]
 [1.]]
(300000, 26)


In [ ]:
y=np.zeros((len(trainy),4))
yt=np.zeros((len(testy),4))
Y4=np.zeros((len(Y4),4))

In [ ]:
for i in range(len(trainy)):
  n = int(trainy[i])
  y[i,n-1] = 1
print(y)  
for i in range(len(testy)):
  n = int(testy[i])
  yt[i,n-1] = 1
print(yt)
for i in range(len(trainy)):
  n = int(trainy[i])
  Y4[i,n-1] = 1  
print(Y4)  

[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:

X_test = testdf.to_numpy()
X_test = (X_test-(np.mean(X_test,axis=0)))/np.std(X_test,axis=0)
print(X_test.shape)

(54320, 26)


In [ ]:
from sklearn.utils import class_weight
y_ints = [y1.argmax() for y1 in y]

class_weights = class_weight.compute_class_weight(
               'balanced',
                np.unique(y_ints), 
                y_ints)
print(class_weights)

[3.46962001e-01 1.80640189e+00 1.77229548e+00 7.50000000e+04]


In [ ]:
class_weight1={0:0,
              1:1,
              2:2.5,
              3:2,
              4:1.5}

In [ ]:
model = Sequential()
model.add(Dense(69, input_dim=n1,activation = 'relu' , kernel_initializer='GlorotUniform', activity_regularizer= l2(0.01)))

model.add(BatchNormalization(axis=-1))
model.add(Dense(58,activation = 'relu',kernel_initializer='GlorotUniform'))

model.add(BatchNormalization(axis=-1))
model.add(Dense(39,activation = 'relu',kernel_initializer='GlorotUniform',activity_regularizer= l2(0.01)))


model.add(Dense(4, activation='sigmoid'))

In [ ]:
model1 = Sequential()
model1.add(Dense(69, input_dim=n1,activation = 'relu' , kernel_initializer='GlorotUniform',activity_regularizer= l2(0.2)))

model1.add(BatchNormalization(axis=-1))
model1.add(Dense(58,activation = 'relu',kernel_initializer='GlorotUniform'))
model1.add(BatchNormalization(axis=-1))
model1.add(Dense(34,activation = 'relu',kernel_initializer='GlorotUniform',activity_regularizer= l2(0.2)))


model1.add(BatchNormalization(axis=-1))
model1.add(Dense(4, activation= 'softmax'))

In [ ]:
model1.summary()

Model: "sequential_37"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_195 (Dense)            (None, 69)                1863      
_________________________________________________________________
batch_normalization_113 (Bat (None, 69)                276       
_________________________________________________________________
dense_196 (Dense)            (None, 58)                4060      
_________________________________________________________________
batch_normalization_114 (Bat (None, 58)                232       
_________________________________________________________________
dense_197 (Dense)            (None, 34)                2006      
_________________________________________________________________
batch_normalization_115 (Bat (None, 34)                136       
_________________________________________________________________
dense_198 (Dense)            (None, 4)               

In [ ]:
opt = Adam(learning_rate = 0.00005)
model1.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'],)

In [ ]:
history = model1.fit(X4,Y4,epochs=10)

Epoch 1/10
15278/15278 [==============================] - 36s 2ms/step - loss: 2.4104 - accuracy: 0.6975
Epoch 2/10
15278/15278 [==============================] - 31s 2ms/step - loss: 1.3495 - accuracy: 0.8223
Epoch 3/10
15278/15278 [==============================] - 29s 2ms/step - loss: 1.3592 - accuracy: 0.8235
Epoch 4/10
15278/15278 [==============================] - 29s 2ms/step - loss: 1.4131 - accuracy: 0.8246
Epoch 5/10
15278/15278 [==============================] - 34s 2ms/step - loss: 1.4824 - accuracy: 0.8238
Epoch 6/10
15278/15278 [==============================] - 34s 2ms/step - loss: 1.5706 - accuracy: 0.8231
Epoch 7/10
 4473/15278 [=======>......................] - ETA: 24s - loss: 2.0417 - accuracy: 0.8214

KeyboardInterrupt: ignored

In [ ]:
model.summary()

In [ ]:
opt = Adam(learning_rate = 0.001)
model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'],)

In [ ]:
history = model.fit(trainX,y,epochs=10)

In [ ]:
_, train_acc = model.evaluate(trainX, y,verbose= 0 )
print(train_acc)

In [ ]:
def plot_confusion_matrix(cm,
                          target_names,
                          title='Confusion matrix',
                          cmap=None,
                          normalize=True):
    """
    given a sklearn confusion matrix (cm), make a nice plot

    Arguments
    ---------
    cm:           confusion matrix from sklearn.metrics.confusion_matrix

    target_names: given classification classes such as [0, 1, 2]
                  the class names, for example: ['high', 'medium', 'low']

    title:        the text to display at the top of the matrix

    cmap:         the gradient of the values displayed from matplotlib.pyplot.cm
                  see http://matplotlib.org/examples/color/colormaps_reference.html
                  plt.get_cmap('jet') or plt.cm.Blues

    normalize:    If False, plot the raw numbers
                  If True, plot the proportions

    Usage
    -----
    plot_confusion_matrix(cm           = cm,                  # confusion matrix created by
                                                              # sklearn.metrics.confusion_matrix
                          normalize    = True,                # show proportions
                          target_names = y_labels_vals,       # list of names of the classes
                          title        = best_estimator_name) # title of graph

    Citiation
    ---------
    http://scikit-learn.org/stable/auto_examples/model_selection/plot_confusion_matrix.html

    """
    import matplotlib.pyplot as plt
    import numpy as np
    import itertools

    accuracy = np.trace(cm) / float(np.sum(cm))
    misclass = 1 - accuracy

    if cmap is None:
        cmap = plt.get_cmap('Blues')

    plt.figure(figsize=(8, 6))
    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()

    if target_names is not None:
        tick_marks = np.arange(len(target_names))
        plt.xticks(tick_marks, target_names, rotation=45)
        plt.yticks(tick_marks, target_names)

    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]


    thresh = cm.max() / 1.5 if normalize else cm.max() / 2
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        if normalize:
            plt.text(j, i, "{:0.4f}".format(cm[i, j]),
                     horizontalalignment="center",
                     color="white" if cm[i, j] > thresh else "black")
        else:
            plt.text(j, i, "{:,}".format(cm[i, j]),
                     horizontalalignment="center",
                     color="white" if cm[i, j] > thresh else "black")


    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label\naccuracy={:0.4f}; misclass={:0.4f}'.format(accuracy, misclass))
    plt.show()

In [ ]:

yhat_probs = model.predict(testX, verbose=0)

yhat_probs = yhat_probs[:, 0]
yhat_classes = np.argmax(model.predict(testX), axis=-1)
accuracy = accuracy_score(testy, yhat_classes)
print( accuracy)
precision = precision_score(testy, yhat_classes,average= 'weighted')
print( precision)
recall = recall_score(testy, yhat_classes , average= 'weighted')
print( recall)
f1 = f1_score(testy, yhat_classes, average= 'weighted')
print( f1)

0.21728674604723794
0.554853388041048
0.21728674604723794
0.3118951361006691


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
yn = model.predict(trainX)
a2 = np.argmax(yn,axis=1)
a2 = pd.DataFrame(a2)
print(a2.value_counts())
cm =confusion_matrix(y,a2)

In [ ]:
plot_confusion_matrix(cm,[1,2,3,4],normalize= True)

In [ ]:
Y_test=model.predict(X_test, )
Y_test4 = model1.predict(X_test)

In [ ]:
print(Y_test,Y_test4)

In [ ]:
a=np.argmax(Y_test,axis=1)
a4 = np.argmax(Y_test4,axis=1)

In [ ]:

print(a,a4)
for i in range(len(a4)):
  
  if a4[i] == 4 :
    a[i]=4


In [ ]:
print(np.argmax(Y_test))


80112


In [ ]:
print(a)

In [ ]:
print(a,a4)

[0 0 1 ... 0 0 0] [0 0 0 ... 0 0 0]


In [ ]:
print(a+1)
a4 = a4+1

[1 1 2 ... 1 1 1]


In [ ]:
a4=pd.DataFrame(a4)
print(a4.value_counts())

1    53867
2      252
3      201
dtype: int64


In [ ]:
a4.to_csv("predictions1.csv", index = False)